### PR TITLE
Chnages updated

### PR DESCRIPTION
**Pull request by v-anniev**

### CODE REVIEW

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/lync-server-2013-supported-server-migration-paths-and-coexistence-scenarios.md](https://github.com/v-anniev/OfficeDocs-SkypeforBusiness-Test-pr.zh-tw/blob/master/server-2013/lync-server-2013-supported-server-migration-paths-and-coexistence-scenarios.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5Caf56315c-c548-f600-855e-c03f112701d9%5CPullRequest%5C201808240849511850-25%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xz5rJqlo%2FyFnLoyxs495L8gAIPmYzTMtDMwpHuN0CGU%3D&st=2018-08-24T08%3A46%3A55Z&se=2018-09-24T08%3A51%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/lync-server-2013-supported-server-migration-paths-and-coexistence-scenarios.md](https://github.com/v-anniev/OfficeDocs-SkypeforBusiness-Test-pr.zh-tw/blob/master/server-2013/lync-server-2013-supported-server-migration-paths-and-coexistence-scenarios.md) | :white_check_mark:Succeeded | |
[server-2013/toc.yml](https://github.com/v-anniev/OfficeDocs-SkypeforBusiness-Test-pr.zh-tw/blob/master/server-2013/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5Caf56315c-c548-f600-855e-c03f112701d9%5CPullRequest%5C201808240905192763-25%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Fgn5jmeEJJGQR%2BfVq%2Ft9%2Fd%2F6XAYGPIuhS9m6Mmfpjeg%3D&st=2018-08-24T09%3A02%3A38Z&se=2018-09-24T09%3A07%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by DanMSFT** [comment]
Adding the file to the TOC is not approved.  Please remove the TOC change.

**Comment by DanMSFT** [comment]
Closing PR, due to undesireable addition to TOC.  New PR created by Hemant.

**Pull request closed without merging**
